---
- name: Install dnf packages
  become: true
  dnf:
    name:
      # essential build tools (gcc, make, etc)
      - "@development-tools"
      - libtool
      - python
      - python3

      # For bluetooth selinux fix
      - selinux-policy
      - python-libselinux

      # Audio / CRAS dependencies
      - acpid
      - libudev-devel
      - sbc-devel
      - alsa-lib-devel
      - iniparser-devel
      - ladspa-devel
      - speex-devel
      - speexdsp-devel
      # We will use podman to build cras in ubuntu 19.04
      - podman
    state: latest
